const DATA = {
  /* ── Meta ── */
  meta: {
    title: 'Mono — Portfolio',
    description: 'One problem at a time. CS student, builder-in-progress.',
    ogTitle: 'Mono — Portfolio',
    ogDesc: 'CS student and builder-in-progress.'
  },

  /* ── Nav ── */
  nav: {
    logo: 'M',
    links: [
      { label: 'About', href: '#about' },
      { label: 'Work', href: '#projects' },
      { label: 'Learning', href: '#learning' },
      { label: 'Contact', href: '#contact' },
    ],
  },

  /* ── Sections ── */
  sections: {
    about: { num: '01', label: 'About' },
    skills: { num: '02', label: 'Skills & Tools' },
    projects: { num: '03', label: 'Projects' },
    learning: { num: '04', label: 'Currently Learning' },
    notes: { num: '05', label: 'Notes' },
  },

  projectFilters: [
    { label: 'All', value: 'all' },
    { label: 'WebDev', value: 'web' },
    { label: 'GameDev', value: 'game' },
    { label: 'Data', value: 'data' },
    { label: 'Utils', value: 'util' },
  ],

  /* ── Identity ── */
  identity: {
    handle: 'Mono',
    name: 'Mikel Taopa',
    year: 'Class of 2030',
    course: 'Computer Science',
    location: 'Antipolo City, Rizal',
    eyebrow: 'CS Student · Builder in progress',
    tagline: 'One problem at a time.',
    taglineSub: 'Currently: all of them.',
    ctaLine: "I'm here. No one can stop me.",
    hintText: '↑ words drift and merge on their own',
    email: 'mikel.taopa@gmail.com',
    contactHeadline: "Let's talk.",
    contactSub: 'Always open to interesting conversations, collaborations, and opportunities.',
    footerText: 'Built from scratch.',
  },

  links: {
    github: 'https://github.com/disposably-mono',
    linkedin: 'https://www.linkedin.com/in/mikel-taopa-a86205359/',
    instagram: 'https://www.instagram.com/disposablymono/',
    facebook: 'https://www.facebook.com/MikelTaopa',
    resume: 'assets/resume.pdf',
  },

  bio: [
    "I'm Mikel, also known as Mono. I'm an incoming Computer Science freshman who believes that what separates the good from the best isn't just skill, but rather vision. I have a knack for building things that are intuitive, innovative, and genuinely well-made.",
    "I don't just want to write code that works; I want to build things that feel right, solve real problems, and leave a mark. One problem at a time.",
  ],

  status: [
    { label: 'Currently', value: 'Incoming CS Student', active: true },
    { label: 'Previously', value: 'Alumni @ Our Lady of Peace School', active: false },
  ],

  skills: [
    {
      group: 'Languages',
      tags: ['Python', 'JavaScript', 'HTML', 'CSS', 'SQL'],
      exploring: false,
    },
    {
      group: 'Tools',
      tags: ['Git', 'Terminal', 'VS Code', 'NeoVim', 'Claude Code', 'MS Excel', 'MS Powerpoint',],
      exploring: false,
    },
    {
      group: 'Setup',
      tags: ['Linux', 'Fedora', 'Gnome',  'Kitty', 'LazyVim',],
      exploring: false,
    },
    {
      group: 'Exploring',
      tags: ['TypeScript', 'SQLite', 'PostgreSQL', 'Prisma', 'NumPy', 'React', 'Next.js', 'Node.js', 'Docker'],
      exploring: true,
    },
  ],

  projects: [
    {
      title: 'halal.',
      description: 'A full-stack election management system built for a school of ~2,000 students, replacing manual paper ballot processes with real-time digital voting, live tally monitoring, and automated results publishing.',
      learned: 'Architecting a production-grade system end-to-end — from database schema design and JWT authentication to Docker deployment and real-time polling — while directing AI-assisted development with full ownership of every technical decision.',
      tags: ['web', 'util'],
      stack: ['React', 'Next.js', 'TypeScript', 'PostgreSQL', 'Prisma', 'Tailwind', 'Docker'],
      liveUrl: '#',
      repoUrl: 'https://github.com/disposably-mono/halal',
      featured: true,
    },
    {
      title: 'Shape Shifter',
      description: 'A turn-based, real-time grid-survival game where you jump to matching enemies by shape or colour to eliminate them and build combos. Survive escalating waves, manage your lives, and trigger the SHIFT mechanic to clear the board. Features guest and registered play, a pre-game lobby, global leaderboards, and a full Web Audio synthesis engine.',
      learned: 'Architecting a modular TypeScript game engine from scratch — typed state management, BPM-locked march timers, rule-based combat, knockback resolution, and a delta-based wave trigger system — while integrating Supabase for auth, score persistence, and leaderboards.',
      tags: ['web', 'game'],
      stack: ['TypeScript', 'Vite', 'Supabase', 'PostgreSQL', 'Vercel'],
      liveUrl: 'https://shape-shifter-tau.vercel.app/',
      repoUrl: 'https://github.com/disposably-mono/shape-shifter',
      featured: true,
    },
    {
      title: 'Mono-Dialect',
      description: 'A word-guessing web game with a roguelike run mode, weighted scoring, and social leaderboards. Built under the MONO brand.',
      learned: 'Architected a full-stack Next.js game with JWT-secured scoring, Dockerized Postgres, Auth.js Google OAuth, and a friends system. Implemented server-side game logic, Prisma ORM with Supabase, and TypeScript across the entire app.',
      tags: ['web', 'game'],
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'Prisma', 'PostgreSQL', 'Auth.js', 'Docker'],
      liveUrl: 'https://mono-dialect.vercel.app/',
      repoUrl: 'https://github.com/disposably-mono/mono-dialect',
      featured: false,
    },
    {
      title: 'Mono-Portfolio',
      description: 'A custom-built, data-driven portfolio designed to showcase my projects and learning journey.',
      learned: 'Integrating JavaScript data objects with DOM rendering while maintaining a clean aesthetic.',
      tags: ['web'],
      stack: ['HTML', 'CSS', 'JavaScript'],
      liveUrl: 'https://disposably-mono.github.io/',
      repoUrl: 'https://github.com/disposably-mono/disposably-mono.github.io',
      featured: false,
    },
  ],

  learning: [
    { type: 'Course', title: 'Claude Code in Action', source: 'Anthropic', dot: 'accent' },
    { type: 'Course', title: 'Claude 101', source: 'Anthropic', dot: 'accent' },
    { type: 'Course', title: 'AI Fluency for Students', source: 'Anthropic', dot: 'accent' },
    { type: 'Course', title: 'MOS: PowerPoint Associate (Microsoft 365)', source: 'Microsoft', dot: 'accent' },
    { type: 'Course', title: 'MOS: Excel Associate (Microsoft 365)', source: 'Microsoft', dot: 'accent' },
    { type: 'Topic', title: 'Machine Learning Basics', source: 'Self-directed', dot: 'grey' },
    { type: 'Topic', title: 'Data Structures & Algorithms', source: 'Self-directed', dot: 'grey' },
    { type: 'Framework', title: 'React Fundamentals', source: 'docs.react.dev', dot: 'highlight' },
  ],

  notes: [
    { title: 'The start of my CS journey', date: 'April 4, 2026', url: '#' },
  ],

  particleWords: [
    { text: 'creator', col: '#588157', size: 13 },
    { text: 'builder', col: '#EAF0CE', size: 13 },
    { text: 'student', col: '#8D99AE', size: 12 },
    { text: 'curious', col: '#E5D4ED', size: 12 },
    { text: 'learning', col: '#588157', size: 12 },
    { text: 'coder', col: '#8D99AE', size: 12 },
    { text: 'late nights', col: '#E5D4ED', size: 11 },
    { text: 'thinker', col: '#EAF0CE', size: 12 },
    { text: 'maker', col: '#588157', size: 13 },
    { text: 'explorer', col: '#8D99AE', size: 11 },
    { text: 'debugger', col: '#E5D4ED', size: 11 },
    { text: 'dreamer', col: '#EAF0CE', size: 12 },
    { text: 'problem solver', col: '#588157', size: 11 },
    { text: 'freshman', col: '#8D99AE', size: 11 },
    { text: 'grower', col: '#E5D4ED', size: 12 },
    { text: 'hacker', col: '#EAF0CE', size: 12 },
    { text: 'overthinker', col: '#E5D4ED', size: 11 },
    { text: 'minimalist', col: '#8D99AE', size: 12 },
    { text: 'night owl', col: '#EAF0CE', size: 11 },
    { text: 'self-taught', col: '#588157', size: 12 },
    { text: 'Filipino', col: '#E5D4ED', size: 12 },
    { text: 'simplifier', col: '#EAF0CE', size: 12 },
    { text: 'always asking', col: '#8D99AE', size: 11 },
    { text: 'bug chaser', col: '#588157', size: 11 },
    { text: 'keyboard warrior', col: '#E5D4ED', size: 11 },
    { text: 'still figuring', col: '#8D99AE', size: 11 },
    { text: 'web curious', col: '#EAF0CE', size: 11 },
    { text: 'ai enthusiast', col: '#588157', size: 11 },
    { text: 'notion addict', col: '#8D99AE', size: 11 },
    { text: 'reader', col: '#E5D4ED', size: 12 },
    { text: 'shipping soon', col: '#588157', size: 11 },
    { text: 'iteration', col: '#EAF0CE', size: 12 },
    { text: 'resilient', col: '#588157', size: 12 },
    { text: 'courageous', col: '#E5D4ED', size: 12 },
    { text: 'empathetic', col: '#EAF0CE', size: 12 },
    { text: 'visionary', col: '#8D99AE', size: 12 },
    { text: 'fun', col: '#588157', size: 11 },
    { text: 'adaptable', col: '#E5D4ED', size: 12 },
    { text: 'straightforward', col: '#EAF0CE', size: 11 },
    { text: 'independent', col: '#8D99AE', size: 12 },
    { text: 'hands-on', col: '#588157', size: 11 },
  ],

  particleMerges: [
    ['curious', 'builder', 'curious builder'],
    ['student', 'late nights', 'learning the hard way'],
    ['creator', 'coder', 'creative technologist'],
    ['thinker', 'maker', 'thoughtful maker'],
    ['dreamer', 'builder', 'builder of dreams'],
    ['explorer', 'debugger', 'bug hunter'],
    ['maker', 'hacker', 'maker-hacker'],
    ['problem solver', 'coder', 'elegant engineer'],
    ['curious', 'explorer', 'endlessly curious'],
    ['creator', 'dreamer', 'visionary creator'],
    ['freshman', 'late nights', 'first year grind'],
    ['grower', 'learning', 'always growing'],
    ['night owl', 'coder', 'midnight coder'],
    ['Filipino', 'builder', 'building from Antipolo'],
    ['minimalist', 'coder', 'clean code only'],
    ['self-taught', 'curious', 'relentlessly self-taught'],
    ['overthinker', 'builder', 'think then build'],
    ['ai enthusiast', 'curious', 'chasing intelligence'],
    ['reader', 'thinker', 'read to build'],
    ['shipping soon', 'builder', 'shipping is learning'],
    ['simplifier', 'problem solver', 'elegantly simple'],
    ['iteration', 'grower', 'improve every loop'],
  ],
};
